### PR TITLE
Fix scraping server

### PR DESCRIPTION
**Pull request by kamalkish0r**
## Describe your changes and upload screenshots if changes on frontend/UI.
- Only single instance of Scraper class will be created. Previously a new instance was created on each request.
- Added logging.
## Issue ticket number and link

Issue Fixes : #issue_number

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

### CODE REVIEW

**Review by kamalkish0r — COMMENTED** [review]
revisited the changes

**Review by kamalkish0r — COMMENTED** [review]
reviewed!

**Review by kanha638 — APPROVED** [review]
👍🏻 Looks good to me.

**Comment by kamalkish0r** [comment]
But not all unit tests are passing!

**Review by kamalkish0r — COMMENTED** [review]
revisited.

**Review by kamalkish0r — COMMENTED** [review]
Revisited changes before merging!

**Pull request merged**
