### PR TITLE
fixed error handling bugs in scrapping server

### PR DESCRIPTION
**Pull request by kamalkish0r**
## Describe your changes and upload screenshots if changes on frontend/UI.
- Fixed bugs occurred while error handling on scrapping server
- Added more meaningful error messages
- Modified function doc strings

## Issue ticket number and link

Issue Fixes : #issue_number

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

### CODE REVIEW

**Comment by kamalkish0r** [comment]
@kanha638 please review and suggest possible changes
You would need to make some changes on public server to display the error messages.

**Comment by kanha638** [comment]
👍🏻 
Getting correct messages now:
Screenshot 2023-05-27 at 5 30 30 PM
Screenshot 2023-05-27 at 5 31 24 PM

**Review by kanha638 — APPROVED** [review]
👍🏻  Okay ready to merge.

**Comment by kanha638** [comment]
> @kanha638 please review and suggest possible changes You would need to make some changes on public server to display the error messages.

It has been handled already actually you was not in sync with main that is why in your system error messages were not showing so i this branch with main

**Review by kanha638 — APPROVED** [review]

**Pull request merged**
